### ISSUE TITLE
Range Error : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rameshrc** [avallete/cypress-nhover#14]
I have application with lit-html web component. When button is clicked on a test bed html, dialog (lit-html web component) appears with ok button. I am trying to hover over it. Since no solutions of hover work for me, i tried out "cypress-nhover": "1.0.0",

  cy.get('dialog').get('.ok-button', { includeShadowDom: true }).nhover()
It creates an error
get .ok-button
scrollIntoView {log: false}
RangeError
Maximum call stack size exceeded

View stack trace
Print to console
at Sizzle (http://localhost:8002/__cypress/runner/cypress_runner.js:85876:27)
at Function.Sizzle.matches (http://localhost:8002/__cypress/runner/cypress_runner.js:86505:10)
at Function.jQuery.filter (http://localhost:8002/__cypress/runner/cypress_runner.js:87883:22)
at winnow (http://localhost:8002/__cypress/runner/cypress_runner.js:87866:22)
at jQuery.fn.init.is (http://localhost:8002/__cypress/runner/cypress_runner.js:87919:13)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151206:16)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)
at findScrollableParent (http://localhost:8002/__cypress/runner/cypress_runner.js:151214:11)

**Comment by avallete** [comment]
Hi,

cypress-nhover doesn't do any special thing to handle shadowDOM, that is probably the cause of the error.

If you can provide a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) either into another repo or some third party public environment (like stackblitz.com) it may be a good start for me to investigate what is the root of the crash.

**Comment by rameshrc** [comment]
> Hi,
> 
> cypress-nhover doesn't do any special thing to handle shadowDOM, that is probably the cause of the error.
> 
> If you can provide a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example) either into another repo or some third party public environment (like stackblitz.com) it may be a good start for me to investigate what is the root of the crash.

Please find test repo in here [lithtml](https://github.com/rameshrc/testinglithtml)

**Comment by rameshrc** [comment]
Sorry forgot to add test files. Added them now

**Comment by avallete** [comment]
Thank's for your help @rameshrc. I know it sounds like a ping-pong game, but the issue doesn't seem to come from the plugin itself. (see my comment here https://github.com/cypress-io/cypress/issues/7986).

I'll be trying to find a way to fix the root of this issue into cypress. I may also try to look for a quick and dirty fix who would make the call to `scrollIntoView` optional to avoid this error.

**Comment by avallete** [comment]
After trying some tests, the issue isn't only due to `scrollIntoView`(even if it's the first part). Because when I remove the call from the command, then the command fails to retrieve the component into the shadowDom via CDP.

Right now I don't have any clue about how to deal with that, it will require more digging and a bunch of time. To understand how to make it work.

**Comment by avallete** [comment]
Related opened issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1107096
